data:
  scans_path: '/data/ScanNet/scans/'
  label_path: '/output/scannet200_text/'
  camera:
    poses_path: '/data/ScanNet/scene_example/pose'
    intrinsic_path: '/data/ScanNet/scene_example/intrinsic/intrinsic_color.txt'
    intrinsic_resolution: [968, 1296]
  depths:
    depths_path: '/data/ScanNet/scene_example/depth/'
    depths_ext: '.png'
    depth_scale: 1000
  images:
    images_path: '/data/ScanNet/scene_example/color/'
    images_ext: '.jpg'
  superpoints:
    top_num: 200

hyperparameters:
  overlapping_ratio: 0.5
  overlapping_score_threshold: 0.5
  top_k: 5
  multi_level_expansion_ratio: 0.1
  num_of_levels: 3
  vis_threshold: 0.2
  frequency: 10
  num_random_rounds: 10
  num_selected_points: 5
  temperature: 0.45

external:
  sam_checkpoint: '/workspace/OV-SAM3D/sam_checkpoints/sam_vit_h_4b8939.pth'
  sam_model_type: 'vit_h'
  clip_model: 'ViT-L/14@336px'

output:
  output_mask: '/output/ovsam3d/scannet200/masks'
  output_feature: '/output/ovsam3d/scannet200/mask_features'